---
image: docker:///concourse/static-golang

inputs:
  - name: cf-resource
    path: gopath/src/github.com/concourse/cf-resource
  - name: autopilot
    path: gopath/src/github.com/concourse/autopilot
  - name: cf-cli
    path: gopath/src/github.com/concourse/cf-cli

run:
  path: gopath/src/github.com/concourse/cf-resource/scripts/ci
