---
image: docker:///concourse/static-golang

inputs:
  - name: cf-resource
    path: gopath/src/github.com/concourse/cf-resource

run:
  path: gopath/src/github.com/concourse/cf-resource/scripts/test
